### ISSUE TITLE
Could not find a declaration file for module 'html-express-js'

### ISSUE THREAD

**Issue by berto-dev** [markcellus/html-express-js#31] opened 2023-06-21 11:01 UTC
**the message:**
```
Could not find a declaration file for module 'html-express-js'. 'p:/js-node-collection/node-base-server/node_modules/html-express-js/src/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/html-express-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'html-express-js';`ts(7016)
module "p:/js-node-collection/node-base-server/node_modules/html-express-js/src/index"
```

**how to check:**
- make a js file
- set `import { html } from 'html-exress-js'`
- so... vscode warning you of problem

**the problem:**
html-express-js it isn't declarated module on import**

**how I try to solve it:**
for me, it's possibile to resolve it via:
-1 make a .d.ts
-2 put inside: `declare module 'html-express-js';`
However it isn't a solution. I don't get if problem is relative of vscode or effectly it isn't declareted.

**Comment by berto-dev** [comment] 2023-06-21 13:09
Update: apparently the .d.ts need to be inside src folder, the same of index.js

**Comment by markcellus** [comment] 2024-03-12 17:41
Hey! Thanks for filing. Creating a JS file and importing would give you this error if you haven't installed the package. Is the html-express-js package installed with `npm install html-express-js` first? Going to close this for now since I'm not getting that error when the package properly installed. But feel free to reopen if you can update your steps to outline exactly how to reproduce the error.

**Closed by markcellus** 2024-03-12 17:41 UTC
